const _STATION_STATUS_ENUMERATIONS = {
    VALID: '現存測站',
    INVALID: '已撤銷',
}

const _DATA_MODEL_ENUMERATIONS = {
    AUTHORIZATION: 'Authorizations',
    STATION: 'Stations',
    OBSERVATION: 'Observations',
}

exports.STATION_STATUS_ENUMERATIONS = _STATION_STATUS_ENUMERATIONS
exports.DATA_MODEL_ENUMERATIONS = _DATA_MODEL_ENUMERATIONS
